/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.*;
import static java.lang.Integer.parseInt;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Britos
 */
public class NuevoAlquiler extends javax.swing.JFrame {
    private MenuPrincipal miMenu;
    private Inmueble inmueblerecibido = new Inmueble ();
    private Garante  garanteEncontrado = new Garante();
    private Locatario locatarioEncontrado = new Locatario ();
    private Locador locadorEncontrado = new Locador();
    private SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yy",Locale.US);
    private SimpleDateFormat print = new SimpleDateFormat("MMM d, yyyy HH:mm:ss");
    private Date fechaActual = new Date();


    /**
     * Creates new form MenuCrearAlquiler
     */
    public NuevoAlquiler(MenuPrincipal miMenuP) {
         this.miMenu = miMenuP;
        initComponents();
         txt_fechaActual.setText(sdf.format(fechaActual));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLocador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_dniLocador = new javax.swing.JTextField();
        txt_nombreLocador = new javax.swing.JTextField();
        txt_dniLocatario = new javax.swing.JTextField();
        btn_buscarLocatario = new javax.swing.JButton();
        btn_buscarLocador = new javax.swing.JButton();
        txt_dniGarante = new javax.swing.JTextField();
        btn_buscarGarante = new javax.swing.JButton();
        btn_nuevoLocador = new javax.swing.JButton();
        btn_nuevoLocatario = new javax.swing.JButton();
        btn_nuevoGarante = new javax.swing.JButton();
        btn_inmueble = new javax.swing.JButton();
        txt_inmueble = new javax.swing.JTextField();
        txt_nombreLocatario = new javax.swing.JTextField();
        txt_nombreGarante = new javax.swing.JTextField();
        txt_direccionInmueble = new javax.swing.JTextField();
        cmb_duracion = new javax.swing.JComboBox<>();
        txt_montoAlquiler = new javax.swing.JTextField();
        txt_recargoProporcional = new javax.swing.JTextField();
        txt_montoComision = new javax.swing.JTextField();
        txt_montoAranceles = new javax.swing.JTextField();
        txt_montoRecargoFijo = new javax.swing.JTextField();
        cmb_tipoPago = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_fechaActual = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btn_crear = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        cmb_primerFechaPago = new javax.swing.JComboBox<>();
        cmb_segundaFechaPago = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txt_tipoInmueble = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_fechaFinalizacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Contrato de alquiler");

        lblLocador.setText("Locador");

        jLabel2.setText("Locatario");

        jLabel3.setText("Garante");

        jLabel4.setText("Inmueble");

        jLabel1.setText("Monto del alquiler");

        jLabel5.setText("Monto de recargo fijo");

        jLabel6.setText("Recargo Proporcional");

        jLabel7.setText("Monto por comision");

        jLabel8.setText("Monto de aranceles");

        jLabel9.setText("Duracion (Meses)");

        txt_nombreLocador.setEditable(false);

        btn_buscarLocatario.setText("Buscar");
        btn_buscarLocatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarLocatarioActionPerformed(evt);
            }
        });

        btn_buscarLocador.setText("Buscar");
        btn_buscarLocador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarLocadorActionPerformed(evt);
            }
        });

        btn_buscarGarante.setText("Buscar");
        btn_buscarGarante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarGaranteActionPerformed(evt);
            }
        });

        btn_nuevoLocador.setText("Nuevo");
        btn_nuevoLocador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoLocadorActionPerformed(evt);
            }
        });

        btn_nuevoLocatario.setText("Nuevo");
        btn_nuevoLocatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoLocatarioActionPerformed(evt);
            }
        });

        btn_nuevoGarante.setText("Nuevo");
        btn_nuevoGarante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoGaranteActionPerformed(evt);
            }
        });

        btn_inmueble.setText("Agregar");
        btn_inmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inmuebleActionPerformed(evt);
            }
        });

        txt_inmueble.setEditable(false);

        txt_nombreLocatario.setEditable(false);

        txt_nombreGarante.setEditable(false);

        txt_direccionInmueble.setEditable(false);
        txt_direccionInmueble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_direccionInmuebleActionPerformed(evt);
            }
        });

        cmb_duracion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "18", "24", "30", "-" }));
        cmb_duracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_duracionActionPerformed(evt);
            }
        });

        cmb_tipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unico", "Mensual" }));

        jLabel10.setText("Tipo de Pago");

        jLabel11.setText("Fecha del contrato");

        jLabel12.setText("Primera fecha de vencimiento del pago");

        jLabel13.setText("Segunda fecha de vencimiento del pago");

        txt_fechaActual.setEditable(false);
        txt_fechaActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_fechaActualActionPerformed(evt);
            }
        });

        jLabel14.setText("Nombre Locador");

        jLabel15.setText("Nombre Locatario");

        jLabel16.setText("Nombre Garante");

        jLabel17.setText("Direccion del Inmueble");

        btn_crear.setText("Crear");
        btn_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        cmb_primerFechaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia 7", "Dia 10" }));
        cmb_primerFechaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_primerFechaPagoActionPerformed(evt);
            }
        });

        cmb_segundaFechaPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia 14", "Dia 17" }));

        jLabel18.setText("Tipo Inmueble");

        txt_tipoInmueble.setEditable(false);

        jLabel19.setText("Fecha de Finalización");

        txt_fechaFinalizacion.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLocador)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_dniLocador)
                            .addComponent(txt_dniLocatario)
                            .addComponent(txt_dniGarante)
                            .addComponent(txt_inmueble)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmb_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19))
                            .addComponent(txt_montoAlquiler)
                            .addComponent(txt_montoComision)
                            .addComponent(txt_montoAranceles)
                            .addComponent(txt_montoRecargoFijo, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_recargoProporcional, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_buscarLocador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_buscarLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10)
                            .addComponent(btn_inmueble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_buscarGarante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(cmb_tipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_crear, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_nuevoGarante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel18)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_nuevoLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_nuevoLocador, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_tipoInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_direccionInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel14))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txt_nombreGarante, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_nombreLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_nombreLocador, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_fechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(cmb_primerFechaPago, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(cmb_segundaFechaPago, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                                .addGap(157, 157, 157))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_fechaFinalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLocador)
                            .addComponent(txt_dniLocador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nombreLocador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_buscarLocador)
                            .addComponent(btn_nuevoLocador)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_dniLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_buscarLocatario)
                            .addComponent(btn_nuevoLocatario)
                            .addComponent(txt_nombreLocatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_dniGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_buscarGarante)
                            .addComponent(btn_nuevoGarante)
                            .addComponent(txt_nombreGarante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_inmueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_direccionInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)
                            .addComponent(btn_inmueble)
                            .addComponent(jLabel18)
                            .addComponent(txt_tipoInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cmb_duracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_fechaFinalizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_montoAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_fechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_recargoProporcional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cmb_primerFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txt_montoComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmb_tipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(cmb_segundaFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_montoAranceles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_montoRecargoFijo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_crear)
                    .addComponent(btn_salir))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void txt_fechaActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_fechaActualActionPerformed

    }//GEN-LAST:event_txt_fechaActualActionPerformed

    private void btn_buscarLocadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarLocadorActionPerformed
          if (txt_dniLocador.getText().isEmpty() ) {
              JOptionPane.showMessageDialog(null, "Ingrese el Dni");
              }else{
                int dni =parseInt(txt_dniLocador.getText());
        try {
            locadorEncontrado =this.miMenu.getMiControlador().BuscarLocador(dni);
            txt_nombreLocador.setText (locadorEncontrado.getApellido() + "  " + locadorEncontrado.getNombre());
                    } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "El Dni no existe\n"+"("+ ex +")");
        }
          }
          
              
          
    }//GEN-LAST:event_btn_buscarLocadorActionPerformed

    private void btn_buscarLocatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarLocatarioActionPerformed
     if (txt_dniLocatario.getText().isEmpty() ) {
              JOptionPane.showMessageDialog(null, "Ingrese el Dni");
              }else{
                int dni =parseInt(txt_dniLocatario.getText());
        try {
            locatarioEncontrado =this.miMenu.getMiControlador().BuscarLocatario(dni);
            txt_nombreLocatario.setText (locatarioEncontrado.getApellido() + "  " + locatarioEncontrado.getNombre());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "El Dni no existe\n"+"("+ ex +")");
        }
          }
    }//GEN-LAST:event_btn_buscarLocatarioActionPerformed

    private void btn_buscarGaranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarGaranteActionPerformed
        if (txt_dniGarante.getText().isEmpty() ) {
              JOptionPane.showMessageDialog(null, "Ingrese el Dni");
              }else{
              int dni =parseInt(txt_dniGarante.getText());
        try {
            garanteEncontrado =this.miMenu.getMiControlador().BuscarGarante(dni);
            txt_nombreGarante.setText (garanteEncontrado.getApellido() + "  " + garanteEncontrado.getNombre());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "El Dni no existe\n"+"("+ ex +")");
        }
          }
    }//GEN-LAST:event_btn_buscarGaranteActionPerformed

    private void txt_direccionInmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_direccionInmuebleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_direccionInmuebleActionPerformed

    private void btn_inmuebleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inmuebleActionPerformed
        NuevoInmueble nuevoInmueble= new NuevoInmueble(this);
        nuevoInmueble.setVisible(true);
           nuevoInmueble.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_inmuebleActionPerformed

    private void btn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearActionPerformed
         Date fechaInicio = new Date ();
         Date fechaFinal = new Date ();
            if ((txt_dniGarante.getText().isEmpty() || txt_nombreGarante.getText().isEmpty() || txt_dniLocador.getText().isEmpty() || txt_nombreLocador.getText().isEmpty() || txt_dniLocatario.getText().isEmpty()  || txt_nombreLocatario.getText().isEmpty()  || txt_inmueble.getText().isEmpty() )
              ||( txt_direccionInmueble.getText().isEmpty() || txt_montoAlquiler.getText().isEmpty() || txt_recargoProporcional.getText().isEmpty() || txt_montoComision.getText().isEmpty()  || txt_montoAranceles.getText().isEmpty() || txt_montoRecargoFijo.getText().isEmpty() )){    
                      JOptionPane.showMessageDialog(null, "Todos los campos son OBLIGATORIOS");
         }else{
        int dniGarante = parseInt(txt_dniGarante.getText());
        int dniLocador = parseInt(txt_dniLocador.getText());
        int dniLocatario = parseInt(txt_dniLocatario.getText());
        String nombreLocatario = txt_nombreLocatario.getText();
        int idInmueble =parseInt(txt_inmueble.getText());
        double montoAlquiler =  Double.parseDouble(txt_montoAlquiler.getText());
        double recargoProporcional = Double.parseDouble(txt_recargoProporcional.getText());
        double montoComision = Double.parseDouble(txt_montoComision.getText());
        int tipoPagoComision = cmb_tipoPago.getSelectedIndex();
        double montoAranceles = Double.parseDouble(txt_montoAranceles.getText());
        double recargoFijo = Double.parseDouble(txt_montoRecargoFijo.getText());
                 try {
                fechaInicio = sdf.parse(txt_fechaActual.getText());
                fechaFinal =sdf.parse(txt_fechaFinalizacion.getText());
            } catch (ParseException ex) {
                Logger.getLogger(NuevoAlquiler.class.getName()).log(Level.SEVERE, null, ex);
            }
             int fechaPago1 = cmb_primerFechaPago.getSelectedIndex();
             if (fechaPago1 == 0){
                 fechaPago1= 7;
             }if (fechaPago1 == 1){
                 fechaPago1 = 10;
             }
             int fechaPago2 = cmb_segundaFechaPago.getSelectedIndex();
              if (fechaPago2 ==0){
                 fechaPago2= 14;
             }if (fechaPago2 == 1){
                 fechaPago2 = 17;
             }
             int duracion = 0;
        switch (cmb_duracion.getSelectedIndex()){
            case 0:  duracion = 18;
                break;
            case 1 : duracion = 24;
                break;
            case 2:  duracion = 30;
                  break;             
                               }
            
             try {
                 miMenu.controlador.CrearAlquiler (dniGarante, dniLocador, dniLocatario, nombreLocatario, idInmueble, montoAlquiler, recargoProporcional, montoComision,
                         tipoPagoComision, montoAranceles,recargoFijo, fechaInicio , fechaFinal ,fechaPago1,fechaPago2, duracion);
                  JOptionPane.showMessageDialog(null, "Creado Correctamente");
             } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error ("+ ex + ")");
             }
             //////////Limpiar campos
    txt_direccionInmueble.setText("");
    txt_dniGarante.setText("");
   txt_dniLocador.setText("");
     txt_dniLocatario.setText("");
     txt_fechaFinalizacion.setText("");
     txt_inmueble.setText("");
   txt_montoAlquiler.setText("");
   txt_montoAranceles.setText("");
    txt_montoComision.setText("");
   txt_montoRecargoFijo.setText("");
     txt_nombreGarante.setText("");
     txt_nombreLocador.setText("");
    txt_nombreLocatario.setText("");
   txt_recargoProporcional.setText("");
    txt_tipoInmueble.setText("");
     
      
        
        }
        
    }//GEN-LAST:event_btn_crearActionPerformed

    private void btn_nuevoGaranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoGaranteActionPerformed
      NuevoGarante nuevoGarante = new NuevoGarante(this.miMenu);
        nuevoGarante.setVisible(true);
           nuevoGarante.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_nuevoGaranteActionPerformed

    private void btn_nuevoLocatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoLocatarioActionPerformed
        NuevoLocatario nuevolocatario = new NuevoLocatario(this.miMenu);
        nuevolocatario.setVisible(true);
           nuevolocatario.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_nuevoLocatarioActionPerformed

    private void btn_nuevoLocadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoLocadorActionPerformed
        NuevoLocador nuevoLocador = new NuevoLocador(this.miMenu);
        nuevoLocador.setVisible(true);
           nuevoLocador.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_nuevoLocadorActionPerformed

    private void cmb_duracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_duracionActionPerformed
   Date fechaFinalizacion = new Date ();  
  int duracion;
        switch (cmb_duracion.getSelectedIndex()){
            case 0:  duracion = 18;
         fechaFinalizacion =  miMenu.controlador.SumarMeses(fechaActual,duracion);
          txt_fechaFinalizacion.setText(sdf.format(fechaFinalizacion));
                break;
            case 1 : duracion = 24;
             fechaFinalizacion =  miMenu.controlador.SumarMeses(fechaActual,duracion);
             txt_fechaFinalizacion.setText(sdf.format(fechaFinalizacion));
                break;
            case 2:  duracion = 30;
             fechaFinalizacion =  miMenu.controlador.SumarMeses(fechaActual,duracion);
             txt_fechaFinalizacion.setText(sdf.format(fechaFinalizacion));
                break;
        }
        
    }//GEN-LAST:event_cmb_duracionActionPerformed

    private void cmb_primerFechaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_primerFechaPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_primerFechaPagoActionPerformed

    
    ////////////////////////////////////////metodos para NuevoInmueble
    
    public void CrearInmuebleA(String tipoInmueble, String calle, String numero, int piso, String barrio, String localidad, int codigoPostal ) throws Exception{
   miMenu.controlador.CrearInmueble(tipoInmueble,  calle,  numero,  piso,  barrio,  localidad,  codigoPostal );
                              } 
    
    public void RecibirInmuebleCreado () throws Exception{
        inmueblerecibido = miMenu.controlador.UltimoInmueble();
        txt_inmueble.setText(String.valueOf(inmueblerecibido.getIdInmueble()));
        txt_tipoInmueble.setText(inmueblerecibido.getTipoInmueble());
        txt_direccionInmueble.setText(inmueblerecibido.getDireccion().toString());
    }

    
   

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscarGarante;
    private javax.swing.JButton btn_buscarLocador;
    private javax.swing.JButton btn_buscarLocatario;
    private javax.swing.JButton btn_crear;
    private javax.swing.JButton btn_inmueble;
    private javax.swing.JButton btn_nuevoGarante;
    private javax.swing.JButton btn_nuevoLocador;
    private javax.swing.JButton btn_nuevoLocatario;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cmb_duracion;
    private javax.swing.JComboBox<String> cmb_primerFechaPago;
    private javax.swing.JComboBox<String> cmb_segundaFechaPago;
    private javax.swing.JComboBox<String> cmb_tipoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLocador;
    private javax.swing.JTextField txt_direccionInmueble;
    private javax.swing.JTextField txt_dniGarante;
    private javax.swing.JTextField txt_dniLocador;
    private javax.swing.JTextField txt_dniLocatario;
    private javax.swing.JTextField txt_fechaActual;
    private javax.swing.JTextField txt_fechaFinalizacion;
    private javax.swing.JTextField txt_inmueble;
    private javax.swing.JTextField txt_montoAlquiler;
    private javax.swing.JTextField txt_montoAranceles;
    private javax.swing.JTextField txt_montoComision;
    private javax.swing.JTextField txt_montoRecargoFijo;
    private javax.swing.JTextField txt_nombreGarante;
    private javax.swing.JTextField txt_nombreLocador;
    private javax.swing.JTextField txt_nombreLocatario;
    private javax.swing.JTextField txt_recargoProporcional;
    private javax.swing.JTextField txt_tipoInmueble;
    // End of variables declaration//GEN-END:variables
}
